Question 1:  What is Logistic Regression, and how does it differ from Linear
Regression?

-->Logistic Regression is a statistical method for predicting a categorical outcome variable based on a set of predictor variables, while Linear Regression predicts a continuous outcome variable

Question 2: Explain the role of the Sigmoid function in Logistic Regression.

-->acts as a squashing function that maps the output of a linear equation to a probability between 0 and 1

Question 3: What is Regularization in Logistic Regression and why is it needed?

-->Regularization in Logistic Regression is a technique that prevents a model from overfitting by adding a penalty term to the loss function, which discourages large coefficient values.
It is needed because without it, a logistic regression model, especially with many features, can become too complex and fit the training data too closely, leading to poor performance on new, unseen data.

Question 4: What are some common evaluation metrics for classification models, and
why are they important?

-->Common evaluation metrics for classification models include the Confusion Matrix, Accuracy, Precision, Recall, F1-Score, and AUC-ROC Curve. These metrics are crucial because they provide a quantitative understanding of a model's performance, allowing for model comparison, improvement, and selection to ensure the deployed model aligns with the specific goals of the classification task, especially when dealing with imbalanced datasets

Question 5: Write a Python program that loads a CSV file into a Pandas DataFrame,
splits into train/test sets, trains a Logistic Regression model, and prints its accuracy.

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.datasets import load_iris
data = load_iris()
df = pd.DataFrame(data.data,columns=data.feature_names)
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [2]:
df['target'] = data.target
df

     sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[150 rows x 5 columns]

In [3]:
x = df.drop('target',axis = 1)
y = df['target']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30,random_state=1)
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.9777777777777777

Question 6:  Write a Python program to train a Logistic Regression model using L2
regularization (Ridge) and print the model coefficients and accuracy.

In [11]:
import pandas as pd
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
x,y = make_classification(n_samples = 1000,n_features=10,n_informative=5,n_redundant=0,random_state=1)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30,random_state=1)
model = LogisticRegression(penalty = 'l2',C = 1.0,solver = 'liblinear',random_state =1)
model.fit(x_test,y_test)
y_pred = model.predict(x_test)
print(model.coef_)
print(accuracy_score(y_test,y_pred))

[[-0.72813375 -0.21766657 -0.01204531 -0.58377497  0.61709955  0.19045341
  -0.03340676 -1.17476138  0.02830521 -0.01609175]]
0.8133333333333334

Question 7: Write a Python program to train a Logistic Regression model for multiclass
classification using multi_class='ovr' and print the classification report.

In [12]:
from sklearn.datasets import load_iris
data = load_iris()
df = pd.DataFrame(data.data,columns = data.feature_names)
df['target'] = data.target
x = df.drop('target',axis = 1)
y = df['target']
x_test,x_train,y_test,y_train = train_test_split(x,y,test_size=0.30,random_state=1)
model = LogisticRegression(multi_class = 'ovr',solver = 'liblinear',max_iter= 200,random_state = 1)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       0.94      0.94      0.94        32
           2       0.95      0.95      0.95        37

    accuracy                           0.96       105
   macro avg       0.96      0.96      0.96       105
weighted avg       0.96      0.96      0.96       105

Question 8: Write a Python program to apply GridSearchCV to tune C and penalty
hyperparameters for Logistic Regression and print the best parameters and validation
accuracy.

In [11]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV,train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score

x,y = make_classification(n_samples=1000, n_features=20, n_informative=10, n_redundant=5, random_state=1)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30,random_state=1)

param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2']
}

model = LogisticRegression(solver='liblinear', random_state=1)

grid_search = GridSearchCV(estimator=model, param_grid=param_grid, cv=5, scoring='accuracy')

grid_search.fit(x_train,y_train)

print("Best parameters: ", grid_search.best_params_)
print("Best cross-validation accuracy: ", grid_search.best_score_)

best_model = grid_search.best_estimator_
y_pred = best_model.predict(x_test)
test_accuracy = accuracy_score(y_test, y_pred)
print("Test accuracy with best parameters: ", test_accuracy)

Best parameters:  {'C': 0.1, 'penalty': 'l2'}
Best cross-validation accuracy:  0.9014285714285715
Test accuracy with best parameters:  0.8966666666666666

Question 9: Write a Python program to standardize the features before training Logistic
Regression and compare the model's accuracy with and without scaling.

In [13]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

x,y = make_classification(n_samples=1000,n_features = 10,n_informative = 5,n_redundant=0,random_state = 1)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.30,random_state =1)

model_unscaled = LogisticRegression(solver = 'liblinear',random_state = 1)
model_unscaled.fit(x_train,y_train)
y_pred_unscaled = model_unscaled.predict(x_test)
unscaled_accuracy_score= accuracy_score(y_test,y_pred_unscaled)
print(f'Accuracy without scaling: {unscaled_accuracy_score}')

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

model_scaled = LogisticRegression(solver = 'liblinear',random_state = 1)
model_scaled.fit(x_train_scaled,y_train)
y_pred_scaled = model_scaled.predict(x_test_scaled)
scaled_accuracy_score = accuracy_score(y_test,y_pred_scaled)
print(f'Accuracy with scaling: {scaled_accuracy_score}')

if unscaled_accuracy_score < scaled_accuracy_score:
  print('Scaled model accuracy is better')
elif unscaled_accuracy_score > scaled_accuracy_score:
  print('Scaled model accuracy is not better')
else:
  print('Model accuracy is equal')

Accuracy without scaling: 0.8133333333333334
Accuracy with scaling: 0.8166666666666667
Scaled model accuracy is better

Question 10: Imagine you are working at an e-commerce company that wants to
predict which customers will respond to a marketing campaign. Given an imbalanced
dataset (only 5% of customers respond), describe the approach you’d take to build a
Logistic Regression model — including data handling, feature scaling, balancing
classes, hyperparameter tuning, and evaluating the model for this real-world business
use case.

In [2]:

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (confusion_matrix, classification_report,
                             roc_auc_score, precision_recall_curve, auc)

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

from sklearn.datasets import make_classification
X, y = make_classification(n_samples=10000, n_features=20, n_informative=10,
                           n_redundant=5, n_classes=2, weights=[0.95, 0.05],
                           random_state=42)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("smote", SMOTE(random_state=42)),
    ("clf", LogisticRegression(solver="liblinear", class_weight="balanced"))
])

param_grid = {
    "clf__C": [0.01, 0.1, 1, 10],
    "clf__penalty": ["l1", "l2"]
}

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

grid = GridSearchCV(pipe, param_grid, cv=cv, scoring="f1", n_jobs=-1, verbose=1)
grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV F1 Score:", grid.best_score_)

y_pred = grid.predict(X_test)
y_prob = grid.predict_proba(X_test)[:, 1]

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("ROC-AUC Score:", roc_auc_score(y_test, y_prob))

# Precision-Recall AUC
prec, rec, _ = precision_recall_curve(y_test, y_prob)
pr_auc = auc(rec, prec)
print("PR-AUC Score:", pr_auc)

Fitting 5 folds for each of 8 candidates, totalling 40 fits
Best Parameters: {'clf__C': 0.1, 'clf__penalty': 'l1'}
Best CV F1 Score: 0.32746422448770995

Confusion Matrix:
 [[1582  310]
 [  20   88]]

Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.84      0.91      1892
           1       0.22      0.81      0.35       108

    accuracy                           0.83      2000
   macro avg       0.60      0.83      0.63      2000
weighted avg       0.95      0.83      0.88      2000

ROC-AUC Score: 0.8831728134053716
PR-AUC Score: 0.5748904775574766